config/routes.rb
SampleApp::Application.routes.draw do
  resources :users do
    member do
      get :following, :followers
    end    
  end
  resources :sessions,      only: [:new, :create, :destroy]
  resources :microposts,    only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]

  match '/signup',  to: 'users#new',            via: 'get'

  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/help',    to: 'static_pages#help',    via: 'get'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  root 'static_pages#home'

end

app/views/layouts/_footer.html.slim
footer class="footer"
  small
    | <a href="http://railstutorial.org/">Rails Tutorial</a>
      by Michael Hartl
  nav
    ul
      li = link_to "About",   about_path
      li = link_to "Contact", contact_path
      li <a href="http://news.railstutorial.org/">News</a>

app/views/layouts/_header.html.slim
header.navbar.navbar-fixed-top.navbar-inverse
  .navbar-inner
    .container
      = link_to "tweeter app", root_path, id: "logo"
      nav
        ul.nav.pull-right.navbar-nav
          li = link_to "Home", root_path
          li = link_to "Help", help_path
          - if signed_in?
            li = link_to "Users", users_path
            li#fat-menu.dropdown
              a.dropdown-toggle[href="#" data-toggle="dropdown"]
                |  Account 
                b.caret
              ul.dropdown-menu
                li = link_to "Profile", current_user
                li = link_to "Settings", edit_user_path(current_user)
                li.divider
                li = link_to "Sign out", signout_path, method: "delete"
          - else
            li = link_to "Sign in", signin_path

app/views/layouts/_shim.html.slim
/[if lt ID 9]
  script src="http://html5shim.googlecode.com/svn/trunk/html5.js"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      = full_title(yield(:title))
    = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = render 'layouts/shim'
  body
    = render 'layouts/header'
    div.container
      - flash.each do | key, value|
        = content_tag(:div, value, class: "alert alert-#{key}")
      = yield
      = render 'layouts/footer'
      = debug(params) if Rails.env.development?